heat_template_version: 2015-04-30

description: Simple template to deploy a single compute instance

parameters:
  keypair:
    type: string
    label: Key Name
    description: Name of key-pair to be used for compute instance
    default: prueba-keypair
  image:
    type: string
    label: Image ID
    description: Image to be used for compute instance 
    default: prueba-cirros
  flavor:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    default: m1.little
  secgroup:
    type: string
    label: Security group
    description: Security group to be used for the instance
    default: prueba-secgroup
  net:
    type: string
    description: The network for the VM
    default: net_mgmt

resources:
  intace_create_by_heat:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair }
      image: { get_param: image }
      flavor: { get_param: flavor }
      security_group: { get_param: secgroup }
      networks: [{network: {get_param: net} }]
